<!-- Menu :: Navigation -->
<?php

	echo 
	$this -> partial(
		'widgets/navigation.phtml', 
		array(
			'label'	=> 'Number of journal', 
			'items'	=> array(
				array(
					'label'	=> 'List', 
					'uri'	=> '/journal/' . $this -> journal[ 'id' ] . '/numbers'
				)
			)
		)
	);

?>

<div class = "content">

	<div class = "errors">
		<?php if( !empty( $this -> errors[ 'filesystem' ] ) ): ?>
		<ul>
			<?php foreach( $this -> errors[ 'filesystem' ] as $error ): ?>
			<li><?= $this -> translate( $error ); ?></li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
	</div>

	<?php

		echo 
		$this -> partial(
			'widgets/journalNumber/form.phtml', 
			array(
				'action'	=> '/journal/' . $this -> journal[ 'id' ] . '/number/add', 
				'errors'	=> array(
					'volume'	=> $this -> errors[ 'volume' ], 
					'issue'		=> $this -> errors[ 'issue' ]
				), 
				'data'	=> array(
					'volume'	=> $this -> data[ 'volume' ], 
					'issue'		=> $this -> data[ 'issue' ]
				)
			)
		);
	
	?>
	
</div>
