
<?php
	
	echo 
	$this -> partial(
		'widgets/navigation.phtml', 
		array(
			'label'	=> 'Article', 
			'items'	=> array(
				array(
					'label'	=> 'List', 
					'uri'	=> '/articles'
				)
			)
		)
	);

?>

<div class = "content">
	<div style = "text-align: left;">
		<div class = "message">
			<?= $this -> translate( 'Choose file from your article in TeX for upload and click Upload button' ); ?>			
		</div>
	
	<form action = "/article/add" method = "post" enctype="multipart/form-data">
	
		<div class = "" style = "line-height: 21pt;">
			<label style = "font-size:x-large;"><?= $this -> translate( 'Article' ); ?>:</label>
			<input style = "font-size:18pt;" type = "file" name = "article"/>	
			<!-- Submit -->
			<input class = "submit" type = "submit" value = "<?= $this -> translate( 'Upload' ); ?>" style = "font-size:18pt;" />
		</div>
		
	</form>
	
	</div>
	
	<div class = "messages">
	
		<ul>	
			<?php foreach( $this -> errors as $err_command => $part ): ?>
				<?php foreach( $part as $part_name => $val ): ?>
				<li>
					<i>Command:</i> <b><?= $err_command; ?></b>, 
					<i>part:</i> <b><?= $part_name; ?></b>, 
					<i>msg:</i> <b><?= $val; ?></b>
				</li>
				<?php endforeach; ?>
			<?php endforeach; ?>
		</ul>
	
	</div>
</div>