
<?php
	
	echo 
	$this -> partial(
		'widgets/navigation.phtml', 
		array(
			'label'	=> 'Article', 
			'items'	=> array(
				array(
					'label'	=> 'List', 
					'uri'	=> '/articles'
				), 
				array(
					'label'	=> 'Add', 
					'uri'	=> '/article/add'
				), 
				array(
					'label'	=> 'Delete', 
					'uri'	=> '/article/' . $this -> article[ 'id' ] . '/delete'
				), 
				array(
					'label'	=> 'Edit', 
					'uri'	=> '/article/' . $this -> article[ 'id' ] . '/edit/'
				), 
				array(
					'label'	=> 'Add to journal', 
					'uri'	=> '/article/' . $this -> article[ 'id' ] . '/addtojournal/'
				)				
			)
		)
	);

?>

<!-- Article :: View -->
<div class = "article">

	<!-- Title -->
	<div class = "title">
		<?= $this -> article[ 'ArticleLanguage' ][ 0 ][ 'title' ]; ?>
	</div>
	
	<div class = "authors">
		<?= $this -> article[ 'ArticleLanguage' ][ 0 ][ 'author' ]; ?>
	</div>
	
	<div class = "params">		
			
		<div class = "language">
			<?= $this -> article[ 'code_language' ]; ?>
		</div>
		|
		<div class = "creation">
			<?= $this -> article[ 'creation' ]; ?>
		</div>
	</div>
	
	<div class = "status">
		<?php
			if( isset( $this -> article[ 'id_journal_number' ] ) )
			{
				echo 'Publisher';
			}else
				{
					echo 'Accepted';					
				}
		?>
	</div>
	
	<div class = "abstract">
		<?= $this -> article[ 'ArticleLanguage' ][ 0 ][ 'abstract' ]; ?>
	</div>
	
	<!-- Download -->
	<div class = "download">
	
		<label>Download:</label>
		<a href = "">pdf</a>, 
		<a href = "">dvi</a>
	
	</div>

</div>