<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Jms_Recension', 'doctrine');

/**
 * Jms_BaseRecension
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_user
 * @property integer $id_article
 * @property string $code_language
 * @property timestamp $creation
 * @property Jms_User $User
 * @property Jms_Article $Article
 * @property Doctrine_Collection $RecensionLanguage
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Jms_BaseRecension extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('recension');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('id_user', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('id_article', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('code_language', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('creation', 'timestamp', null, array(
             'type' => 'timestamp',
             'fixed' => false,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Jms_User as User', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Jms_Article as Article', array(
             'local' => 'id_article',
             'foreign' => 'id'));

        $this->hasMany('Jms_RecensionLanguage as RecensionLanguage', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}