<!-- Registration -->
<!-- Form -->
<form action = "/registration" method = "post">

	<!-- Base data -->	
	<div id = "" class = "group">
	
		<label class = "group-title"><?= $this -> translate( 'Base date' ); ?>:</label>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Username' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "username" type = "text" name = "username" value = "<?= $this -> input[ 'username' ]; ?>" required />
			</div>
			<span id = "username-msg" class = "registration-item-message">
				<?=
					implode( '<br />', $this -> errors[ 'username' ] );
					/*foreach( $this -> errors[ 'username' ] as $error )
					{
						echo $this -> translate( $error );
					}*/				
				?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Password' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "" type = "password" name = "password" value = "" required />
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'password' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Repeat password' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "" type = "password" name = "repeat_password" value = "" required />
			</div>			
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'r_passwd' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Gender' ); ?>:</label>
			<div class = "registration-item-field">
				<div>					
					<input id = "gender-male" type = "radio" name = "gender" value = "1" <?//= ($this -> input[ 'gender' ] == 1) ? 'checked' : ''; ?> required />
					<label for = "gender-male">Male</label>
				</div>
				
				<div>				
					<input id = "gender-female" type = "radio" name = "gender" value = "0" <?//= ($this -> input[ 'gender' ] == '0') ? 'checked' : ''; ?> required />
					<label for = "gender-female">Female</label>
				</div>
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'gender' ] );	?>
			</span>
		</div>
		
	</div>
	
	<!-- Names -->
	<div class = "group">
	
		<label class = "group-title"><?= $this -> translate( 'Names' ); ?>:</label>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'First name' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "first_name" value = "<?= $this -> input[ 'first_name' ]; ?>" required />
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'first_name' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Last name' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "second_name" value = "<?= $this -> input[ 'second_name' ]; ?>" required />
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'last_name' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Middle name' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "father_name" value = "<?= $this -> input[ 'father_name' ]; ?>" required />
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'middle_name' ] );	?>
			</span>
		</div>
		
	</div>
	
	
	<!-- Contacts -->
	<div class = "group">
	
		<label class = "group-title"><?= $this -> translate( 'Contacts' ); ?>:</label>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'E-mail' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "email" type = "email" name = "email" value = "<?= $this -> input[ 'email' ]; ?>" required />
			</div>
			<span id = "email-msg" class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'email' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Phone' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "phone" value = "<?= $this -> input[ 'phone' ]; ?>" />
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'phone' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Skype' ); ?>:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "skype" value = "<?= $this -> input[ 'skype' ]; ?>" />
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'skype' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Mailling Address' ); ?>:</label>
			<div class = "registration-item-field">
				<textarea id = "" name = "address" cols = "30" rows = "5" required><?= $this -> input[ 'address' ]; ?></textarea>
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'mailing_address' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Country' ); ?>:</label>
			<div class = "registration-item-field">
				<select id = "" name = "country" required>
					<option value = "UA">Ukraine</option>
					<!-- TODO: Get From DB -->
				</select>
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'country' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Language' ); ?>:</label>
			<div class = "registration-item-field">
				<select id = "" name = "language" required>
					<option value = "uk">Ukraine</option>
					<!-- TODO: Get From DB -->
				</select>
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'language' ] );	?>
			</span>
		</div>
		
		<!-- Role -->
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Role' ); ?>:</label>
			<div class = "registration-item-field">
				<select id = "" name = "role" required>
					<?php foreach( $this -> roles as $role ): ?>
					<option value = "<?= $role[ 'id' ]; ?>"><?= $role[ 'title' ]; ?></option>
					<?php endforeach; ?>
				</select>
			</div>
			<span class = "registration-item-message">
				<?= implode( '<br />', $this -> errors[ 'role' ] );	?>
			</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title"><?= $this -> translate( 'Params' ); ?>:</label>
			<div class = "registration-item-field">
				<div>
					<input id = "" type = "checkbox" name = "" />
					<label><?= $this -> translate( 'Send me a letter' ); ?></label>
				</div>
				<div>
					<input id = "" type = "checkbox" name = "" />
					<label><?= $this -> translate( 'Other' ); ?></label>
				</div>
			</div>
			<span class = "registration-item-message">
				<?=
					$this -> translate(
						$this -> errors[ 'params' ]
					);				
				?>
			</span>
		</div>
		
	</div>
	
	<input type = "submit" name = "" value = "Send" />

</form>
