<!-- Registration -->
<div id = "" class = "">Main => Registration</div>

<!-- Title -->
<h1>Registration</h1>

<!-- Form -->
<form action = "" method = "post">
	
	<div id = "" class = "group">
	
		<label class = "group-title">Base:</label>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title">Username:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "" value = "" />
			</div>
			<span class = "registration-item-message">Msg<br/>fd</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title">Password:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "" value = "" />
			</div>
			<span class = "registration-item-message"></span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title">Repeat password:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "" value = "" />
			</div>			
			<span class = "registration-item-message">Msg</span>
		</div>
		
	</div>
	
	
	<div class = "group">
	
		<label class = "group-title">Names:</label>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title">First name:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "" value = "" />
			</div>
			<span class = "registration-item-message">Msg</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title">Second name:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "" value = "" />
			</div>
			<span class = "registration-item-message">Msg</span>
		</div>
		
		<div class = "registration-item">
			<label for = "" class = "registration-item-title">Middle name:</label>
			<div class = "registration-item-field">
				<input id = "" type = "text" name = "" value = "" />
			</div>
			<span class = "registration-item-message">Msg</span>
		</div>
		
	</div>
	
	<input type = "submit" name = "" value = "Send" />

</form>