<!-- Template -->
<html>

	<head>
	
		<meta/>
	
		<title>JMS</title>
		
		
		<!-- Library -->
		<!-- jQuery -->
		<link rel="stylesheet" href="/client/library/jQuery/jquery-ui.css"
			type="text/css" media="all" />
		<script type="text/javascript"
			src="/client/library/jQuery/jquery.min.js"></script>
		<script type="text/javascript"
			src="/client/library/jQuery/jquery-ui.min.js"></script>
		<!--
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/ui-lightness/jquery-ui.css" type="text/css" media="all" />
        -->
		
		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		
		<!-- Styles :: CSS -->
		<link type = "text/css" rel = "stylesheet" href = "/client/application/views/styles/main.css" />
				
		<!-- Dynamic styles -->
		<?= $this -> headLink(); ?>
		
		
		<!-- Scripts :: JS -->
		<script type = "text/javascript">
			$( document ).ready( 
				function(){
					//alert( 'main' );
					//TODO:
					$( ".pager>a" ).button();
				}
			);
		</script>
		
		<!-- Dynamic JS -->
		<?= $this -> headScript(); ?>
		
	</head>
	
	<body>
	
		<div id = "header" class = "header">
			
			<!-- Manu :: Main -->
			<div id = "menu-main" class = "menu-main">
				
				<?= $this -> navigation() -> menu(); ?>				
			
			</div>
			
			<!-- Authorization block -->
			<div id = "auth" class = "auth">
			
				<?php if( !isset( $this -> user ) ): ?>
				<a href = "/login">Sing in</a> | 
				<a href = "/registration">Sing up</a>
				<?php else: ?>
				<a><?= $this -> user[ 'first_name' ]; ?></a> | 
				<a href = "/logout"><?= $this -> translate( 'Sign out' ); ?></a>
				<?php endif; ?>
			
			</div>
			
			<!-- Tools -->
			<div id = "tools" class = "tools">
			
				
			
			</div>
			
		</div>
		
		<!-- Short logotip -->
		<div id = "logotip" class = "logotip">
		
			<?php
				if( isset( $this -> logotip ) )
				{
					echo $this -> logotip;
				}
			?>
			<!--Carpathian Mathematical Publications-->
		
		</div>
		
		<!-- Main content -->
		<div id = "main" class = "main">
		
			<!-- Path on site -->
			<div id = "" class = "">
				<?=
					$this -> navigation() 
						-> breadcrumbs() 
						-> setLinkLast( false ) 
						-> setSeparator( ' / ' ); 
				?>
			</div>

			<!-- Title -->
			<!--<h1><?= $this -> Title; ?></h1>-->
			
			<!-- Content -->
			<?= $this -> layout() -> content; ?>
			
		</div>
		
		<!-- Footer -->
		<div id = "footer" class = "footer">
		
			&copy; 2013 by <a href = "">Vitaliy Tsutsman</a>
			<br />
			<a href = "">About</a>
		
		</div>
	
	</body>

</html>