<!-- Template -->
<html>

	<head>
	
		<meta/>
	
		<title>JMS</title>
		
		<link />
		
		<script type = "text/javascript"></script>
	
	</head>
	
	<body>
	
	<div id = "header">
	
		<div id = "menu-main">
		
			Home
		
		</div>
		
		<div id = "logotip">
		
		
		
		</div>
		
	</div>
	
	<div id = "main">
	
		
	
	</div>
	
	<div id = "footer">
	
	
	
	</div>

		<?php echo $this -> layout() -> content; ?>
	
	</body>

</html>