<?php echo $this->doctype(); ?>

<html lang="en">

	<head>

        <meta charset="utf-8">
		<meta http-equiv = "Content-Type" content = "text/html; charset=utf-8" />

		<meta name="robots" content="ALL" />

        <!-- Dynamic -->
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Title -->
        <?php echo $this->headTitle('JMS ' ) ?>
	
		<link type="image/x-icon" rel="shortcut icon" href="/favicon.ico" />	
		
		<!-- Library -->
		<!-- jQuery -->
		<link rel="stylesheet" href="/client/library/jQuery/jquery-ui.css"
			type="text/css" media="all" />
		<script type="text/javascript"
			src="/client/library/jQuery/jquery.min.js"></script>
		<script type="text/javascript"
			src="/client/library/jQuery/jquery-ui.min.js"></script>
		<!--
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/ui-lightness/jquery-ui.css" type="text/css" media="all" />
        -->
		
		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		
		<!-- Styles :: CSS -->
		<link type = "text/css" rel = "stylesheet" href = "/client/application/views/styles/main.css" />
        	
		<!-- Dynamic styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath() . '/css/style.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        ?>
		
		
		<!-- Scripts :: JS -->
		<script type = "text/javascript">
			$( document ).ready( 
				function(){
					//alert( 'main' );
					//TODO:
					//$( ".pager>a" ).button();
				}
			);
		</script>
		
		<!-- Dynamic JS -->
        <?php echo $this->headScript()
//            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
//            ->prependFile($this->basePath() . '/js/jquery.min.js')
//            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
		
	</head>
	
	<body>
	
		<div id = "header" class = "header">
			
            <!-- Logotip -->
            <span = "logotip">
                <img src="<?php echo $this->basePath('img/zf2-logo.png') ?>"/>
            </span>
            
			<!-- Manu :: Main -->
			<div id = "menu-main" class = "menu-main">
				
                <ul>
                    <li>Home</li>
                </ul>
				<?= $this -> navigation() -> menu() -> setRenderParents( true ); ?>
			
			</div>
			
			<!-- Authorization block -->
			<div id = "auth" class = "auth">
				<?php if( !isset( $this -> user ) ): ?>
				<a href = "/login">         <?= $this -> translate( 'Sign In' ); ?></a> | 
				<a href = "/registration">  <?= $this -> translate( 'Sign Up' ); ?></a>
				<?php else: ?>
				<a><?= $this -> user[ 'first_name' ]; ?></a> | 
				<a href = "/logout"><?= $this -> translate( 'Sign Out' ); ?></a>
				<?php endif; ?>
			</div>
			
			<!-- Tools -->
			<div id = "tools" class = "tools">
			
				
			
			</div>
			
		</div>
        
		<!-- Short logotip -->
		<div id = "logotip" class = "logotip">
		
			<?php
				if( isset( $this -> logotip ) )
				{
					echo $this -> translate( $this -> logotip );
				}
			?>
			Carpathian Mathematical Publications
            
		</div>
		
		<!-- Main content -->
		<div id = "main" class = "main">
		
			<!-- Path on site -->
			<div id = "" class = "breadcrumbs">
				<?=
					$this -> navigation() 
						-> breadcrumbs()
						-> setLinkLast( false ) 
						-> setMinDepth( 0 )
						-> setSeparator( ' / ' ); 
				?>
			</div>

			<!-- Title -->
			<!--<h1><?= $this -> Title; ?></h1>-->
			
			<!-- Content -->
			<?= $this -> content; ?>
			
		</div>
		
		<!-- Footer -->
		<div id = "footer" class = "footer">
		
			&copy; 2013 by <a href = "">Vitaliy Tsutsman</a>
			<br />
			<a href = "">About</a>
			
			<div class = "locale">
				<a href = "/locale/set/en_GB">en_GB</a> | 
				<a href = "/locale/set/en_US">en_US</a> | 
				<a href = "/locale/set/uk_UA">uk_UA</a> | 
				<a href = "/locale/set/ru_RU">ru_RU</a>
			</div>
		
		</div>
	
	</body>

</html>
