<form action = "<?= $this -> action; ?>" method = "post" enctype = "multipart/form-data">

	<div class = "field">
		<label><?= $this -> translate( 'Cover' ); ?>:</label>
		<div>
			<input type = "file" name = "cover" value = "<?= $this -> data[ 'cover' ]; ?>" />
		</div>
		<br/>
		<span><?= implode( '<br />', $this -> errors[ 'cover' ] ) ?></span>
	</div>

	<div class = "field">
		<label><?= $this -> translate( 'ISBN' ); ?>:</label>
		<div>
			<input id = "isbn" type = "text" name = "isbn" value = "<?= $this -> data[ 'isbn' ]; ?>" required />
		</div>
		<span id = "isbn-msg"><?= implode( '<br />', $this -> errors[ 'isbn' ] ) ?></span>
	</div>
	
	<div class = "field">
		<label><?= $this -> translate( 'Title' ); ?>:</label>
		<div>
			<input type = "text" name = "title" value = "<?= $this -> data[ 'title' ]; ?>" required />
		</div>
		<span><?= implode( '<br />', $this -> errors[ 'title' ] ) ?></span>
	</div>
	
	<div class = "field">
		<label><?= $this -> translate( 'Description' ); ?>:</label>
		<div>
			<textarea name = "description" rows="8" cols="40" required><?= $this -> data[ 'description' ]; ?></textarea>
		</div>
		<span><?= implode( '<br />', $this -> errors[ 'description' ] ) ?></span>
	</div>	

	<div class = "field">
		<label></label>
		<div>
			<input type = "submit" value = "Add"/>
		</div>
	</div>

</form>