
<?php
	
	echo 
	$this -> partial(
		'widgets/navigation.phtml', 
		array(
			'label'	=> 'Journal', 
			'items'	=> array(
				array(
					'label'	=> 'List', 
					'uri'	=> '/journals'
				)
			)
		)
	);

?>

<div class = "content">

	<?php
		
		echo 
		$this -> partial(
			'widgets/journal/form.phtml', 
			array(
				'action'	=> '/journal/add', 
				'errors'	=> array(
					'cover'			=> $this -> errors[ 'cover' ], 
					'isbn'			=> $this -> errors[ 'isbn' ], 
					'title'			=> $this -> errors[ 'title' ], 
					'description'	=> $this -> errors[ 'description' ]
				), 
				'data'	=> array(
					'isbn'			=> $this -> data[ 'isbn' ], 
					'title'			=> $this -> data[ 'title' ], 
					'description'	=> $this -> data[ 'description' ]
				)
			)
		);
	
	?>
	
</div>