
<?php
	
	echo 
	$this -> partial(
		'widgets/journal/navigation.phtml', 
		array(
			'label'	=> 'Journal', 
			'items'	=> array(
				array(
					'label'	=> 'List', 
					'uri'	=> '/journal/list'
				), 
				array(
					'label'	=> 'Add', 
					'uri'	=> '/journal/add'
				), 
				array(
					'label'	=> 'Delete', 
					'uri'	=> '/journal/delete/' . $this -> journal[ 'id' ]
				), 
				array(
					'label'	=> 'View', 
					'uri'	=> '/journal/' . $this -> journal[ 'id' ]
				), 
			)
		)
	);

?>

<div class = "content">

	<!-- Logotip(First page) -->
	<img src = "/data/journals/<?= $this -> journal[ 'id' ]; ?>/photo/cover.jpg" 
		width = ""
		style = "max-width : 100%;" 		
	/>

	<div style = "clear : both; margin-top : 10px;">
	<?php
		
		echo 
		$this -> partial(
			'widgets/journal/form.phtml', 
			array(
				'action'	=> '/journal/edit/' . $this -> journal[ 'id' ], 
				'errors'	=> array(
					'cover'			=> $this -> errors[ 'cover' ], 
					'isbn'			=> $this -> errors[ 'isbn' ], 
					'title'			=> $this -> errors[ 'title' ], 
					'description'	=> $this -> errors[ 'description' ]
				), 
				'data'	=> array(
					'isbn'			=> $this -> journal[ 'issn' ], //TODO: ISBN
					'title'			=> $this -> journal[ 'title' ], 
					'description'	=> $this -> journal[ 'description' ]
				)
			)
		);
	
	?>
	</div>
	
</div>