
<?php
	
	echo 
	$this -> partial(
		'widgets/journal/navigation.phtml', 
		array(
			'label'	=> 'Journal', 
			'items'	=> array(
				array(
					'label'	=> 'List', 
					'uri'	=> '/journal/list'
				), 
				array(
					'label'	=> 'Add', 
					'uri'	=> '/journal/add'
				), 
				array(
					'label'	=> 'Delete', 
					'uri'	=> '/journal/delete/' . $this -> journal[ 'id' ]
				), 
				array(
					'label'	=> 'Edit', 
					'uri'	=> '/journal/edit/' . $this -> journal[ 'id' ]
				)
			)
		)
	);

?>

<div class = "journal">
	
	<!-- Logotip(First page) -->
	<img src = "/data/journals/<?= $this -> journal[ 'id' ]; ?>/photo/cover.jpg" 
		width = "240" 
		align = "left" 
	/>
	
	<!-- Info -->
	<div class = "info">
	
		<!-- Title -->
		<div class = "title">
			<?= $this -> journal[ 'title' ]; ?>
		</div>
		
		<!-- ISSN -->
		<div class = "isbn">
			<?= $this -> journal[ 'issn' ]; ?>
		</div>
		
		<!-- Time of create -->
		<div class = "creation">
			<?= $this -> journal[ 'creation' ]; ?>
		</div>
		
		<!-- Description -->
		<div class = "description">
			<?= $this -> journal[ 'description' ]; ?>
		</div>
	
	</div>
	
	<!-- Numbers of journal -->
	<div class = "numbers">
		<label><?= $this -> translate( 'Numbers' ); ?>:</label>
		<?php foreach( $this -> journal[ 'JournalNumber' ] as $number ): ?>
		<div class = "number">
		
			<div class = "volume">
				<?= $this -> translate( 'Volume' );?>: <?= $number[ 'volume' ]; ?>
			</div>
			<div class = "issue">
				<a href = "">
					<?= $this -> translate( 'Issue' );?>: <?= $number[ 'issue' ]; ?>
				</a>
			</div>
		
		</div>
		<?php endforeach; ?>
	
	</div>
		
</div>